# Generated by Django 4.2.4 on 2023-11-20 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('ages', models.CharField(choices=[('20-24', '20~24세'), ('25-29', '25~29세'), ('30-34', '30~34세'), ('35-39', '35~39세'), ('40-44', '40~44세'), ('45-49', '45~49세'), ('50-54', '50~54세'), ('55-59', '55~59세'), ('60+', '60세 이상')], max_length=5)),
                ('gender', models.CharField(choices=[('male', '남성'), ('female', '여성'), ('other', '기타')], max_length=10)),
                ('monthly_income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('additional_income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monthly_expenses', models.DecimalField(decimal_places=2, max_digits=10)),
                ('debt_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('financial_goals', models.CharField(choices=[('savings', '적금'), ('investment', '투자'), ('retirement', '은퇴 준비'), ('education', '교육 자금 마련'), ('other', '기타')], max_length=20)),
                ('risk_tolerance', models.CharField(max_length=10)),
                ('current_financial_products', models.CharField(choices=[('savings_account', '적금'), ('fixed_deposit', '예금'), ('investment_fund', '투자 펀드'), ('retirement_account', '연금 계좌'), ('credit_card', '신용카드'), ('other', '기타')], max_length=20)),
                ('satisfaction_level', models.CharField(max_length=20)),
                ('financial_advice_needed', models.BooleanField(default=False)),
            ],
        ),
    ]
